import Rendomdude from "../assets/img/Png/RendomHen.png";
const MYCARDS_1 = [
  {
    data1: "NFT",
    data1_2: "Holders ",
    data2: "70% ",
    data3: "NFT Holders will earn $TNAT via p2e mechanism. ",
  },
  {
    data1: "Liquidity ",
    data2: "20%",
    data3:
      "20% of $TNAT  token supply will be used for liquidity in exchanges. ",
  },
  {
    data1: "Team",
    data2: "10%",
    data3: "10% of $TNAT token supply is for TNAT team.",
  },
];
export const RandomCards = [
  { head: " Random", span: "Dude", Image: Rendomdude, num: "17%" },
  { head: " Random", span: "Dude", Image: Rendomdude, num: "17%" },
  { head: " Random", span: "Dude", Image: Rendomdude, num: "17%" },
  { head: " Random", span: "Dude", Image: Rendomdude, num: "17%" },
  { head: " Random", span: "Dude", Image: Rendomdude, num: "17%" },
  { head: " Random", span: "Dude", Image: Rendomdude, num: "17%" },
  { head: " Random", span: "Dude", Image: Rendomdude, num: "17%" },
  { head: " Random", span: "Dude", Image: Rendomdude, num: "17%" },
];
export const MYCARD_2 = [
  {
    span1: "01",
    span2: "02",
    data1: "    Lorem Ipsum",
    data2: "   Lorem Ipsum dolor sit amet",
    data3: "    Lorem Ipsum dolor sit amet, consectetur",
    data3_1: "       adipiscing elit, sed do eiusmod tempor",
    data3_2: "     incididunt ut labore et dolore magna aliqua.",
    data4: "    Lorem Ipsum ",
    data5: "   Lorem Ipsum dolor sit amet",
    data6: "    Lorem Ipsum dolor sit amet, consectetur",
    data6_1: "       adipiscing elit, sed do eiusmod tempor",
    data6_2: "     incididunt ut labore et dolore magna aliqua.",
  },
  {
    data1: "   Lorem Ipsum",
    data2: "   Lorem Ipsum dolor sit amet",
    data3: "    Lorem Ipsum dolor sit amet, consectetur",
    data3_1: "       adipiscing elit, sed do eiusmod tempor",
    data3_2: "     incididunt ut labore et dolore magna aliqua.",
    data4: "    Lorem Ipsum ",
    data5: "   Lorem Ipsum dolor sit amet",
    data6: "    Lorem Ipsum dolor sit amet, consectetur",
    data6_1: "       adipiscing elit, sed do eiusmod tempor",
    data6_2: "     incididunt ut labore et dolore magna aliqua.",
    span1: "03",
    span2: "04",
  },
  {
    data1: "   Lorem Ipsum",
    data2: "   Lorem Ipsum dolor sit amet",
    data3: "    Lorem Ipsum dolor sit amet, consectetur",
    data3_1: "       adipiscing elit, sed do eiusmod tempor",
    data3_2: "     incididunt ut labore et dolore magna aliqua.",
    data4: "    Lorem Ipsum ",
    data5: "   Lorem Ipsum dolor sit amet",
    data6: "    Lorem Ipsum dolor sit amet, consectetur",
    data6_1: "       adipiscing elit, sed do eiusmod tempor",
    data6_2: "     incididunt ut labore et dolore magna aliqua.",
    span1: "05",
    span2: "06",
  },
  {
    data1: "    Lorem Ipsum",
    data2: "   Lorem Ipsum dolor sit amet",
    data3: "    Lorem Ipsum dolor sit amet, consectetur",
    data3_1: "       adipiscing elit, sed do eiusmod tempor",
    data3_2: "     incididunt ut labore et dolore magna aliqua.",
    data4: "    Lorem Ipsum ",
    data5: "   Lorem Ipsum dolor sit amet",
    data6: "    Lorem Ipsum dolor sit amet, consectetur",
    data6_1: "       adipiscing elit, sed do eiusmod tempor",
    data6_2: "     incididunt ut labore et dolore magna aliqua.",
    span1: "07",
    span2: "08",
  },
  {
    data1: "    Lorem Ipsum",
    data2: "   Lorem Ipsum dolor sit amet",
    data3: "    Lorem Ipsum dolor sit amet, consectetur",
    data3_1: "       adipiscing elit, sed do eiusmod tempor",
    data3_2: "     incididunt ut labore et dolore magna aliqua.",
    data4: "    Lorem Ipsum ",
    data5: "   Lorem Ipsum dolor sit amet",
    data6: "    Lorem Ipsum dolor sit amet, consectetur",
    data6_1: "       adipiscing elit, sed do eiusmod tempor",
    data6_2: "     incididunt ut labore et dolore magna aliqua.",
    span1: "09",
    span2: "10",
  },
];
export const Faq_DATA = [
  {
    data1: "What is the total The Name supply?",
    data2: "The Total supply is *****.",
  },
  {
    data1: "Where can I buy or sell my The Name?",
    data2: "You can mint them on our website or get them on secondary market.",
  },
  {
    data1: "Where can I buy TNAT$ token?",
    data2: "You can buy across multiple platforms.",
  },
  {
    data1: "Have More Questions?",
    data2: "Join our Discord.",
  },
];
export default MYCARDS_1;
